// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Rp5M6nqPTtvrpjhmZfGOwVH3etf_HbE',
    appId: '1:90677046556:web:e7b64cdc08544fb0c09ed9',
    messagingSenderId: '90677046556',
    projectId: 'proyectosig-d55e8',
    authDomain: 'proyectosig-d55e8.firebaseapp.com',
    storageBucket: 'proyectosig-d55e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqiX7xFO6LNJFndmiIm123noWvAeL17d4',
    appId: '1:90677046556:android:bcec616f81ee8eb0c09ed9',
    messagingSenderId: '90677046556',
    projectId: 'proyectosig-d55e8',
    storageBucket: 'proyectosig-d55e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0HP8lEA83rWgOoKbNGOZAb6eTpwwUtIQ',
    appId: '1:90677046556:ios:c26ae7ff001ceabac09ed9',
    messagingSenderId: '90677046556',
    projectId: 'proyectosig-d55e8',
    storageBucket: 'proyectosig-d55e8.appspot.com',
    iosClientId: '90677046556-d9rnt03dgqqcvsergkmkfkht3gehc4jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
